version: '3'

networks:
  lamp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.20.0/24

services:
  web:
    image: phalconphp/php-apache:ubuntu-16.04
    container_name: phalcon_apache
    ports:
      - "2000:80"
    volumes:
      - ./:/app
    networks:
      - lamp
    links:
      - redis
      - db

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - lamp

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - /data/docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - lamp
    restart: on-failure

